### ISSUE TITLE
.existed() not working properly in Parse Javascript SDK 1.6.4

### ISSUE THREAD

**Issue by dtaitz** [ParsePlatform/Parse-SDK-JS#35]
In the afterSave of my parse object subclasses, I call .existed() on the request object. 

I have had this code for quite a while, but only recently do existing object return false for .existed(). I tried to change the SDK to 1.6.2 and 1.6.0 but still ran into the same issue

**Comment by andrewimm** [comment]
Should be resolved in #36

**Comment by wangmengyan95** [comment]
LGTM

**Comment by dtaitz** [comment]
@stanleyw @andrewimm I am still experiencing this problem in latest. I had to deploy the SDK to 1.5.0 to get rid of the error

**Comment by mohnazemi** [comment]
This bug does not seem to be resolved. Please also see: https://developers.facebook.com/bugs/1675561372679121/
